apiVersion: v1
kind: ConfigMap
metadata:
  name: sonsaekim-config
data:
  LEARNING_SERVICE_URL: "http://learning-service:3000"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  PROGRESS_SERVICE_URL: "http://progress-service:3002"
  AI_SERVICE_URL: "http://ai-service:5000"